import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const dictionaries = {
  ar: {
    languageName: 'العربية',
    switchLanguage: 'English',
    appName: 'نظام إنساني',
    appFullName: 'نظام إدارة العمل الإنساني',
    country: 'اليمن',
    loading: 'جاري التحميل...',
    logout: 'تسجيل خروج',
    delete: 'حذف',
    noData: 'لا توجد بيانات',
    login: 'تسجيل الدخول',
    loginLoading: 'جاري الدخول...',
    loginError: 'اسم المستخدم أو كلمة المرور غير صحيحة',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    demoCredentials: 'بيانات الدخول التجريبية:',
    demoUser: 'المستخدم:',
    demoPassword: 'كلمة المرور:',
    confirmDeleteBeneficiary: 'هل أنت متأكد من حذف هذا المستفيد؟',
    save: 'حفظ',
    addBeneficiary: 'إضافة مستفيد',
    addNewBeneficiary: 'إضافة مستفيد جديد',
    beneficiariesRegistered: 'مستفيد مسجل',
    searchBeneficiaries: 'بحث بالاسم أو رقم الهوية أو رقم الهاتف...',
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
    nationalId: 'رقم الهوية',
    name: 'الاسم',
    gender: 'الجنس',
    phone: 'رقم الهاتف',
    governorate: 'المحافظة',
    district: 'المديرية',
    householdSize: 'حجم الأسرة',
    vulnerabilityScore: 'درجة الضعف',
    vulnerabilityScoreRange: 'درجة الضعف (0-10)',
    status: 'الحالة',
    selectGovernorate: 'اختر المحافظة',
    navMain: 'الرئيسية',
    navProgram: 'إدارة البرامج',
    navAiIntegration: 'الذكاء والتكامل',
    navAdmin: 'الإدارة',
    dashboard: 'لوحة المعلومات',
    dashboardSubtitle: 'مركز قيادة يومي لمتابعة البرامج والعمليات والمخاطر.',
    globalSearch: 'بحث في النظام...',
    quickActions: 'إجراءات سريعة',
    operationalSnapshot: 'ملخص تشغيلي',
    activeProjects: 'المشاريع النشطة',
    employees: 'الموظفون',
    totalGrants: 'إجمالي المنح',
    totalSpent: 'إجمالي المصروفات',
    distributions: 'التوزيعات',
    cashTransfers: 'التحويلات النقدية',
    pendingLeaves: 'إجازات معلقة',
    lowStockItems: 'مواد منخفضة المخزون',
    activeSurveys: 'استبيانات نشطة',
    beneficiariesByGovernorate: 'المستفيدون حسب المحافظة',
    projectsBySector: 'المشاريع حسب القطاع',
    recentBeneficiaries: 'آخر المستفيدين المسجلين',
    recentProjects: 'آخر المشاريع',
    recentTransactions: 'آخر المعاملات المالية',
    viewAll: 'عرض الكل',
    newBeneficiary: 'مستفيد جديد',
    newProject: 'مشروع جديد',
    createReport: 'إنشاء تقرير',
    systemReady: 'النظام جاهز',
    executiveDashboard: 'اللوحة التنفيذية',
    beneficiaries: 'المستفيدين',
    projects: 'المشاريع',
    activities: 'تتبع الأنشطة',
    cash: 'التحويلات النقدية',
    mealPlan: 'خطة MEAL',
    monitoring: 'المتابعة',
    logframe: 'الإطار المنطقي',
    dataCollection: 'جمع البيانات',
    evaluationTools: 'أدوات التقييم',
    needsAssessment: 'تقييم الاحتياجات',
    accountability: 'المساءلة (CFM)',
    safeguarding: 'الحماية و CHS',
    learning: 'التعلم',
    fieldVisits: 'الزيارات الميدانية',
    recommendations: 'التوصيات',
    sectorIndicators: 'المؤشرات القطاعية',
    assessmentTools: 'أدوات التقييم الجاهزة',
    analytics: 'التحليلات',
    reports: 'التقارير',
    aiInsights: 'الذكاء الاصطناعي',
    offlineMode: 'وضع Offline',
    kobo: 'تكامل KoBo',
    remoteMonitoring: 'مراقبة عن بعد',
    feedbackLoop: 'حلقة التغذية الراجعة',
    scheduledReports: 'تقارير مجدولة',
    integrations: 'التكامل الخارجي',
    finance: 'الإدارة المالية',
    hr: 'الموارد البشرية',
    inventory: 'المخازن والتوزيع',
    risks: 'إدارة المخاطر',
    documents: 'أرشيف الوثائق',
    compliance: 'الامتثال والجودة',
    audit: 'سجل التدقيق',
    active: 'نشط',
    inactive: 'غير نشط',
    planned: 'مخطط',
    completed: 'مكتمل',
    suspended: 'معلق',
    cancelled: 'ملغي',
    pending: 'قيد الانتظار',
    approved: 'معتمد',
    rejected: 'مرفوض',
    disbursed: 'تم الصرف',
    received: 'تم الاستلام',
    failed: 'فشل',
    in_progress: 'جاري',
    graduated: 'تخرج',
    on_leave: 'في إجازة',
    terminated: 'منتهي',
    resigned: 'مستقيل',
    male: 'ذكر',
    female: 'أنثى',
    income: 'إيراد',
    expense: 'مصروف',
    transfer: 'تحويل',
    output: 'مخرج',
    outcome: 'نتيجة',
    impact: 'أثر',
  },
  en: {
    languageName: 'English',
    switchLanguage: 'العربية',
    appName: 'Humanitarian System',
    appFullName: 'Humanitarian Aid Management System',
    country: 'Yemen',
    loading: 'Loading...',
    logout: 'Log out',
    delete: 'Delete',
    noData: 'No data available',
    login: 'Log in',
    loginLoading: 'Signing in...',
    loginError: 'Invalid username or password',
    username: 'Username',
    password: 'Password',
    demoCredentials: 'Demo credentials:',
    demoUser: 'User:',
    demoPassword: 'Password:',
    confirmDeleteBeneficiary: 'Are you sure you want to delete this beneficiary?',
    save: 'Save',
    addBeneficiary: 'Add beneficiary',
    addNewBeneficiary: 'Add new beneficiary',
    beneficiariesRegistered: 'registered beneficiaries',
    searchBeneficiaries: 'Search by name, ID number, or phone...',
    firstName: 'First name',
    lastName: 'Last name',
    nationalId: 'National ID',
    name: 'Name',
    gender: 'Gender',
    phone: 'Phone',
    governorate: 'Governorate',
    district: 'District',
    householdSize: 'Household size',
    vulnerabilityScore: 'Vulnerability score',
    vulnerabilityScoreRange: 'Vulnerability score (0-10)',
    status: 'Status',
    selectGovernorate: 'Select governorate',
    navMain: 'Main',
    navProgram: 'Program Management',
    navAiIntegration: 'AI and Integrations',
    navAdmin: 'Administration',
    dashboard: 'Dashboard',
    dashboardSubtitle: 'Daily command center for programs, operations, and risk.',
    globalSearch: 'Search the system...',
    quickActions: 'Quick actions',
    operationalSnapshot: 'Operational snapshot',
    activeProjects: 'Active projects',
    employees: 'Employees',
    totalGrants: 'Total grants',
    totalSpent: 'Total spent',
    distributions: 'Distributions',
    cashTransfers: 'Cash transfers',
    pendingLeaves: 'Pending leaves',
    lowStockItems: 'Low-stock items',
    activeSurveys: 'Active surveys',
    beneficiariesByGovernorate: 'Beneficiaries by governorate',
    projectsBySector: 'Projects by sector',
    recentBeneficiaries: 'Recent beneficiaries',
    recentProjects: 'Recent projects',
    recentTransactions: 'Recent financial transactions',
    viewAll: 'View all',
    newBeneficiary: 'New beneficiary',
    newProject: 'New project',
    createReport: 'Create report',
    systemReady: 'System ready',
    executiveDashboard: 'Executive Dashboard',
    beneficiaries: 'Beneficiaries',
    projects: 'Projects',
    activities: 'Activity Tracker',
    cash: 'Cash Transfers',
    mealPlan: 'MEAL Plan',
    monitoring: 'Monitoring',
    logframe: 'Logframe',
    dataCollection: 'Data Collection',
    evaluationTools: 'Evaluation Tools',
    needsAssessment: 'Needs Assessment',
    accountability: 'Accountability (CFM)',
    safeguarding: 'Safeguarding and CHS',
    learning: 'Learning',
    fieldVisits: 'Field Visits',
    recommendations: 'Recommendations',
    sectorIndicators: 'Sector Indicators',
    assessmentTools: 'Assessment Tools',
    analytics: 'Analytics',
    reports: 'Reports',
    aiInsights: 'AI Insights',
    offlineMode: 'Offline Mode',
    kobo: 'KoBo Integration',
    remoteMonitoring: 'Remote Monitoring',
    feedbackLoop: 'Feedback Loop',
    scheduledReports: 'Scheduled Reports',
    integrations: 'External Integrations',
    finance: 'Finance',
    hr: 'Human Resources',
    inventory: 'Inventory and Distribution',
    risks: 'Risk Management',
    documents: 'Document Archive',
    compliance: 'Compliance and Quality',
    audit: 'Audit Trail',
    active: 'Active',
    inactive: 'Inactive',
    planned: 'Planned',
    completed: 'Completed',
    suspended: 'Suspended',
    cancelled: 'Cancelled',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    disbursed: 'Disbursed',
    received: 'Received',
    failed: 'Failed',
    in_progress: 'In progress',
    graduated: 'Graduated',
    on_leave: 'On leave',
    terminated: 'Terminated',
    resigned: 'Resigned',
    male: 'Male',
    female: 'Female',
    income: 'Income',
    expense: 'Expense',
    transfer: 'Transfer',
    output: 'Output',
    outcome: 'Outcome',
    impact: 'Impact',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'ar');

  useEffect(() => {
    const direction = language === 'ar' ? 'rtl' : 'ltr';
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = direction;
  }, [language]);

  const value = useMemo(() => {
    const t = (key) => dictionaries[language]?.[key] ?? dictionaries.en[key] ?? key;
    return {
      language,
      direction: language === 'ar' ? 'rtl' : 'ltr',
      isRtl: language === 'ar',
      setLanguage,
      toggleLanguage: () => setLanguage((current) => (current === 'ar' ? 'en' : 'ar')),
      t,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
